name: all_printer
description: A new Flutter project.
version: 0.0.1
homepage: https://github.com/taghassan54/all_printer
environment: {sdk: '>=2.17.5 <3.0.0', flutter: '>=2.5.0'}
dependencies:
  flutter: {sdk: flutter}
  plugin_platform_interface:
  permission_handler:
  logger:
  path_provider:
  dio:
  flutter_usb_printer:


dev_dependencies:
  flutter_test: {sdk: flutter}
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android: {package: com.example.all_printer, pluginClass: AllPrinterPlugin}
      ios: {pluginClass: AllPrinterPlugin}
  assets: []
  fonts: []
